// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: grpc_trigger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCTriggerClient is the client API for GRPCTrigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCTriggerClient interface {
	Trigger(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type gRPCTriggerClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCTriggerClient(cc grpc.ClientConnInterface) GRPCTriggerClient {
	return &gRPCTriggerClient{cc}
}

func (c *gRPCTriggerClient) Trigger(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpctrigger.GRPCTrigger/Trigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCTriggerServer is the server API for GRPCTrigger service.
// All implementations must embed UnimplementedGRPCTriggerServer
// for forward compatibility
type GRPCTriggerServer interface {
	Trigger(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGRPCTriggerServer()
}

// UnimplementedGRPCTriggerServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCTriggerServer struct {
}

func (UnimplementedGRPCTriggerServer) Trigger(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedGRPCTriggerServer) mustEmbedUnimplementedGRPCTriggerServer() {}

// UnsafeGRPCTriggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCTriggerServer will
// result in compilation errors.
type UnsafeGRPCTriggerServer interface {
	mustEmbedUnimplementedGRPCTriggerServer()
}

func RegisterGRPCTriggerServer(s grpc.ServiceRegistrar, srv GRPCTriggerServer) {
	s.RegisterService(&GRPCTrigger_ServiceDesc, srv)
}

func _GRPCTrigger_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCTriggerServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctrigger.GRPCTrigger/Trigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCTriggerServer).Trigger(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCTrigger_ServiceDesc is the grpc.ServiceDesc for GRPCTrigger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCTrigger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctrigger.GRPCTrigger",
	HandlerType: (*GRPCTriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _GRPCTrigger_Trigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_trigger.proto",
}
