metadata:
  product_id: Process trigger product
  workflow_id: Process trigger workflow
  process_id: Process trigger process
  version_id: Process trigger version v1.0.0
  base_path: '/Some/Path'

nats:
  url: 'nats://localhost:4222'
  stream: process-trigger
  output: process-trigger-output

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      process: process
      retain-execution-id: true
