metadata:
  product_id: Cronjob trigger product
  workflow_name: Cronjob trigger workflow
  process_name: Cronjob trigger process
  version_tag: Cronjob trigger version v1.0.0
  base_path: '/Some/Path'

nats:
  url: 'nats://localhost:4222'
  stream: cronjob-trigger
  output: cronjob-trigger-output

minio:
  endpoint: "localhost:9000"
  access_key_id: minioadmin
  access_key_secret: minioadmin
  use_ssl: false
  bucket: test-bucket

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      cron: '@every 10s'
      message: 'Hello world'
